version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs

services:
  dind:
    container_name: jenkins-agents
    image: docker:dind
    privileged: true
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - docker
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    
  jenkins:
    container_name: jenkins-controller
    image: mlbarker/jenkins:casc
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - jenkins
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      
      # TODO  Need to migrate these details to secrets.
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=password

